tap "homebrew/bundle"
brew "act"
brew "gh"
brew "openssl@3"
brew "node"
brew "markdownlint-cli", link: false
brew "openssl@1.1"
brew "readline"
brew "pyenv"
brew "sqlite"
brew "tcl-tk"
brew "xz"
brew "yarn"
brew "zlib"
