name: Lint using Rubocop

on:
  push:
    branches:
      - "main"
      - "**/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.7.8

      - name: Install Rubocop
        run: |
             gem install rubocop
