name: Lint using Rubocop

on:
  push:
    branches:
      - "main"
      - "**/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rubocop
        run: |
             ./lint.sh
