name: Lint using Rubocop

on:
  push:
    branches:
      - "main"
      - "**/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Rubocop Linter
        uses: andrewmcodes/rubocop-linter-action@v3.0.0.rc2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
