name: Lint using Rubocop

on:
  push:
    branches:
      - "main"
      - "**/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.7
    
    - name: Install dependencies
      run: gem install rubocop
    
    - name: Run RuboCop
      run: rubocop