name: Lint using Rubocop

on:
  push:
    branches:
      - "!main" # Matches branches other than 'main'
      - "!gh-pages" # Matches branches other than 'gh-pages'
      - "main"
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Send Slack Starting Deployment message
      id: slack-start
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C04JZM55VC2"
        payload: |
          {
            "text": "Deployment started (In Progress)",
            "attachments": [
              {
                "pretext": "Deployment started",
                "color": "dbab09",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "In Progress"
                  },
                  {
                    "title": "Branch",
                    "short": true,
                    "value": "${{ github.ref_name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
    
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Wait for 5 seconds
    #   run: sleep 5

    - name: Logging
      run: |
        echo "${{toJSON(github.event)}}"

    - name: Intentional Fail
      run: nonexistent-command
    
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.7
    
    # - name: Install dependencies
    #   run: gem install rubocop

    # - name: Run RuboCop
    #   run: rubocop

    - name: Send Slack Deployment Complete message (Success)
      if: success()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C04JZM55VC2"
        update-ts: ${{ steps.slack-start.outputs.ts }}
        payload: |
          {
            "text": "Deployment finished (Success)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "#28a745",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Success"
                  },
                  {
                    "title": "Branch",
                    "short": true,
                    "value": "${{ github.ref_name }}"
                  }
                ]
              }
            ]
          }
        
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
    
    - name: Send Slack Deployment Complete message (Failure)
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: "C04JZM55VC2"
        update-ts: ${{ steps.slack-start.outputs.ts }}
        payload: |
          {
            "text": "Deployment finished (FAILURE)",
            "attachments": [
              {
                "pretext": "Deployment finished",
                "color": "danger",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "Failure"
                  },
                  {
                    "title": "Branch",
                    "short": true,
                    "value": "${{ github.ref_name }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}